version: '3'
services:
  db:
     image: mysql
     container_name: mysql_db
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="secret"
  web:
    image: apache
    build: ./apache/
    depends_on:
       - db
    container_name: apache_web
    volumes:
       - ./UNIXROOT/var/www/html:/var/www/html
    restart: always
    ports:
      - "80:80"
  solr:
    image: solr
    build: ./solr/
    volumes:
      - ./UNIXROOT/a:/opt/solr/a
      - ./UNIXROOT/var/www/html/stash/:/stash
    restart: always
    ports:
      - "8983:8983"
      - "8080:8080"
