version: '3'
services:
  apacheweb:
    image: apache
    build: ./apache/
    container_name: apache
    volumes:
       - ./UNIXROOT/html:/var/www/html
       - ./UNIXROOT/stash:/stash
    restart: always
    ports:
      - "80:80"
  blacklight:
   image: blacklight
   build: ./blacklight/
   container_name: blacklight
   volumes:
      - ./UNIXROOT/blacklight-core:/tmp/solr-8.3.0/server/solr/blacklight-core
      - ./UNIXROOT/stash:/stash
   restart: always
   ports:
      - "8983:8983"
      - "3000:3000"
   ulimits:
     nproc: 65535
     nofile:
       soft: 65535
       hard: 70000
