version: '3'
services:
  db:
     image: mysql
     container_name: mysql_db
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="secret"
  web:
    image: apache
    build: ./
    depends_on:
       - db
    container_name: apache_web
    volumes:
       - ./UNIXROOT/var/www/html:/var/www/html
    restart: always
    ports:
      - "80:80"
